import React, { useState } from 'react';

const Component = () => {
  const [clicked, setClicked] = useState(false);
  
  return (
    <div className="p-4">
      <h2 className="text-xl font-bold mb-4">Example Component</h2>
      <p className="mb-2">This is a sample component that was generated by Claude.</p>
      <button 
        className="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded"
        onClick={() => setClicked(!clicked)}
      >
        {clicked ? 'Clicked!' : 'Click Me'}
      </button>
      
      {clicked && (
        <p className="mt-4 text-green-600 animate-pulse">
          The component is working correctly!
        </p>
      )}
    </div>
  );
};

export default Component;